INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '100 Free', '49.05');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '500 Free', '05:05.12');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '1000 Free', '10:35.56');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '1650 Free', '18:11.44');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '100 Fly', '51.8');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '200 Fly', '01:57.14');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '200 Back', '01:55.33');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '100 Breast', '01:05.65');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '200 Breast', '02:21.36');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '200 IM', '01:58.02');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '400 IM', '04:25.04');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '100 Free', '46.47');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '500 Free', '04:39.31');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '1000 Free', '09:51.11');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '100 Fly', '52.84');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '200 Fly', '02:15.01');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '200 Back', '02:00.63');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '200 IM', '01:55.61');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '400 IM', '04:26.49');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '100 Free', '47.23');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '500 Free', '05:03.24');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '100 Fly', '49.82');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '200 Fly', '01:52.46');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '100 Breast', '59.07');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '200 Breast', '02:07.66');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '200 IM', '02:03.76');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '400 IM', '04:18.15');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '100 Free', '49.24');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '500 Free', '04:44.52');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '1000 Free', '09:43.73');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '1650 Free', '16:41.75');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '100 Fly', '53.53');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '200 Fly', '01:54.45');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '200 Back', '01:58.89');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '100 Breast', '01:01.5');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '200 Breast', '02:08.67');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '200 IM', '01:57.10');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '400 IM', '04:08.33');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '100 Free', '47.94');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '100 Fly', '53.03');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '200 Fly', '02:08.44');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '100 Breast', '59.71');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '200 Breast', '02:18.20');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '200 IM', '02:01.66');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '100 Free', '45.79');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '100 Fly', '56.57');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '100 Breast', '01:00.09');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '200 Breast', '02:12.54');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '200 IM', '02:00.22');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '400 IM', '04:30.76');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '100 Free', '48.34');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '500 Free', '04:46.13');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '1000 Free', '09:55.77');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '1650 Free', '16:36.56');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '100 Fly', '53.88');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '200 Fly', '01:58.15');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '200 Back', '02:12.61');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '100 Breast', '01:23.23');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '200 IM', '02:06.03');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '400 IM', '04:30.01');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '100 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '100 Fly', '50.01');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '200 Fly', '01:54.31');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '200 Back', '02:18.43');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '100 Free', '49.01');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '500 Free', '05:11.68');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '100 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '200 Back', '02:01.24');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '100 Breast', '01:06.11');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '200 Breast', '02:34.00');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '200 IM', '02:08.86');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '100 Free', '47.49');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '500 Free', '04:40.98');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '1000 Free', '10:00.45');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '1650 Free', '16:37.76');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '100 Fly', '59.7');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '50 Free', '21.85');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '200 Free ', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '200 Free ', '01:48.98');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '200 Free ', '01:51.09');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '200 Free ', '01:50.76');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '200 Free ', '01:45.03');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '200 Free ', '01:41.21');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '200 Free ', '01:43.27');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '200 Free ', '01:43.60');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '100 Back', '52.97');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Jones, Nick', '100 Back', '53.66');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '100 Back', '58.52');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '100 Back', '55.05');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '100 Back', '52.97');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '200 Fly', '02:09.17');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '400 IM', '04:25.99');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '100 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '100 Fly', '55.09');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '200 Back', '02:03.90');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '100 Breast', '56.08');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '200 Breast', '02:03.10');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '200 IM', '01:53.80');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '400 IM', '04:21.70');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '100 Free', '48.37');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '500 Free', '5.04.29');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '100 Fly', '52.32');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '200 Fly', '02:17.56');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '200 IM', '02:01.07');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '100 Free', '52.15');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '500 Free', '04:49.14');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '100 Fly', '55.99');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '100 Breast', '56.98');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '200 Breast', '02:02.77');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '200 IM', '01:56.62');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '400 IM', '04:05.97');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '100 Free', '49.35');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '100 Fly', '55.06');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '200 Fly', '02:00.89');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '100 Free', '54.11');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '100 Fly', '56.09');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '200 Fly', '02:08.24');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '200 Back', '02:07.70');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '100 Free', '58.84');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '500 Free', '05:10.63');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '1000 Free', '10:32.32');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '1650 Free', '17:44.41');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '100 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '100 Breast', '01:10.35');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '200 Breast', '2.31.88');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '400 IM', '04:39.18');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '100 Free', '01:09.23');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '100 Fly', '01:07.55');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '200 Fly', '02:26.24');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '100 Breast', '01:26.05');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '100 Free', '01:00.15');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '100 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '100 Free', '01:00.72');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '100 Fly', '01:10.82');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '200 Back', '02:47.50');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '100 Free', '56.72');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '200 Free ', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '200 Free ', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '200 Free ', '02:30.78');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '200 Free ', '01:56.40');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '200 Free ', '01:58.82');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '200 Free ', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '200 Free ', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '200 Free ', '01:54.31');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '200 Free ', '01:53.81');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '100 Back', '01:07.97');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '100 Back', '53.93');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '100 Back', '56.55');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '100 Back', '01:09.99');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '500 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '100 Fly', '01:08.45');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '200 Back', '02:12.03');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '100 Breast', '01:15.52');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '100 Free', '52.83');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '500 Free', '05:50.30');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '1000 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '1650 Free', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '100 Fly', '01:01.44');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '200 Fly', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '200 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '100 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '200 Breast', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '200 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '400 IM', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '50 Free', '22.58');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Quiddington, Harvey', '50 Free', '25.22');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Sutton, Hayden', '50 Free', '22.28');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ervin, Aaron', '50 Free', '21.5');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Henderson, Charles ', '50 Free', '22.16');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Moore Yetter, Monty', '50 Free', '23.26');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Crescioni, Landon', '50 Free', '22.87');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '50 Free', '26.35');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ford, Sarah', '50 Free', '26.75');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McLaughin, Natalie', '50 Free', '27.57');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Gary, Logan', '50 Free', '22.53');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Dylan', '50 Free', '20.93');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '50 Free', '23.93');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chemacki, Abbi', '50 Free', '28.3');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Chehebar, Ben', '50 Free', '21.8');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '50 Free', '22.03');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Courville, Olivia', '50 Free', '29.74');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Martinez, Sergio', '50 Free', '21.88');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Turner, Adonis', '50 Free', '25.05');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '50 Free', '21.14');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '200 Free ', '01:56.93');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '200 Free ', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Brunmeier, Shay', '200 Free ', '01:45.44');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('McNamara, Jack', '200 Free ', '01:41.70');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Solbach, Cloe', '100 Back', '01:00.63');
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Streeter, Catherine', '100 Back', null);
INSERT INTO public.best_times (swimmer_name, event_name, time) VALUES ('Ory, Carter', '100 Back', '54.39');
