INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Henderson, Charles ', 'Loyola University New Orleans', 'Dallas, TX', 'M', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Quiddington, Harvey', 'Loyola University New Orleans', 'London, GBR', 'M', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Perfettini, Alex', 'Loyola University New Orleans', 'Nice, FRA', 'M', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Romero, Emma', 'Loyola University New Orleans', 'USA', 'F', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Lavicka, Jossalin', 'Loyola University New Orleans', 'USA', 'F', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Faucheux, Hartley ', 'Loyola University New Orleans', 'New Orleans, LA', 'F', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Courville, Olivia', 'Loyola University New Orleans', 'USA', 'F', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('McLaughin, Natalie', 'Loyola University New Orleans', 'USA', 'F', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Chehebar, Ben', 'Loyola University New Orleans', 'Mandeville, LA', 'M', 'JR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Ory, Carter', 'Loyola University New Orleans', 'Destrehan, LA', 'M', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('McNamara, Jack', 'Loyola University New Orleans', 'Mandeville, LA', 'M', 'JR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Brunmeier, Shay', 'Loyola University New Orleans', 'Clover, SC', 'M', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Streeter, Catherine', 'Loyola University New Orleans', 'Suwanee, GA', 'F', 'JR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Solbach, Cloe', 'Loyola University New Orleans', 'Lake Oswego, OR', 'F', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Gary, Logan', 'Loyola University New Orleans', 'Youngsville, LA', 'M', 'JR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Chehebar, Dylan', 'Loyola University New Orleans', 'Mandeville, LA', 'M', 'JR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Ford, Sarah', 'Loyola University New Orleans', 'Westwego, LA', 'F', 'SO');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Ervin, Aaron', 'Loyola University New Orleans', 'Cypress, TX', 'M', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Crescioni, Landon', 'Loyola University New Orleans', 'Metairie, LA', 'M', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Sutton, Hayden', 'Loyola University New Orleans', 'Los Alamos, NM', 'M', 'SO');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Turner, Adonis', 'Loyola University New Orleans', 'Slidell, LA', 'M', 'FR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Jones, Nick', 'Loyola University New Orleans', 'Saint Petersburg, FL', 'M', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Moore Yetter, Monty', 'Loyola University New Orleans', 'USA', 'M', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Chemacki, Abbi', 'Loyola University New Orleans', 'Bridgeport, CT', 'F', 'SR');
INSERT INTO public.swimmers (swimmer_name, team, hometown, gender, class) VALUES ('Martinez, Sergio', 'Loyola University New Orleans', 'Madrid, ESP', 'M', 'SO');
